name: React CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      -name: Chesckout repository
       uses: actions/Chesckout@v4
      -name: Set up Node.jobs
       uses: actions/setup-node@v4
       with:
          node-verssion: '18'
      -name: npm cirun: npm ci
       run: npm ci
      -name: Install dependencies
       run: npm install vite@latest
      -name: npm ci
       run: npm ci
      -name: Install dependencies
       run: npm install
      -name: Run tests
       run: npm test --if-present
      -name: Build project
       run: npm run build --if-present